# GENERATED BY CHAT. As much as I dislike AI coding, I do not have the time in my day to write this from scratch at the moment.
from typing import List, Tuple, Set
import math
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
import numpy as np
from mpl_toolkits.mplot3d.art3d import Line3DCollection

Junction = Tuple[int, int, int]
Circuit = Set[Junction]
Edge = Tuple[Junction, Junction]

def dist(p1: Junction, p2: Junction) -> float:
    return math.sqrt(
        (p2[0] - p1[0])**2 +
        (p2[1] - p1[1])**2 +
        (p2[2] - p1[2])**2
    )

def get_circuit(circuits: List[Circuit], junction: Junction) -> Tuple[int, Circuit]:
    for i, circuit in enumerate(circuits):
        if junction in circuit:
            return i, circuit
    return -1, None

def get_part_1(s: List[Circuit]) -> int:
    a, b, c = sorted(len(i) for i in s)[-3:]
    return a * b * c

def solve() -> Tuple[int, int]:
    # -----------------------------
    # READ INPUT
    # -----------------------------
    with open("Day_8/input.txt") as file:
        j_boxes: List[Junction] = [tuple(map(int, i.strip().split(','))) for i in file.readlines()]

    # -----------------------------
    # PHASE 1 — PREPROCESS
    # -----------------------------
    dists: List[Tuple[Edge, float]] = sorted(
        [((i, j), dist(i, j)) for b, i in enumerate(j_boxes) for j in j_boxes[b + 1:]],
        key=lambda x: x[1]
    )

    circuits: List[Circuit] = [{i} for i in j_boxes]
    accepted_edges: List[Edge] = []

    p1: int = 0
    i = -1
    while len(circuits) > 1:
        (a, b), _ = dists[i := i + 1]
        if i == 1000:
            p1 = get_part_1(circuits)
        pa, ca = get_circuit(circuits, a)
        if b in ca:
            continue
        pb, cb = get_circuit(circuits, b)
        circuits[pa].update(cb)
        del circuits[pb]
        accepted_edges.append((a, b))

    # Part 2 example
    p2 = a[0] * b[0]

    # -----------------------------
    # PHASE 2 — VISUALIZE
    # -----------------------------
    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111, projection='3d')
    ax.set_facecolor("black")
    fig.patch.set_facecolor("black")
    ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
    ax.grid(False)

    viz_circuits = [{i} for i in j_boxes]

    def viz_get_circuit(j):
        for idx, c in enumerate(viz_circuits):
            if j in c:
                return idx
        raise RuntimeError("Missing junction in viz circuits")

    xs = [p[0] for p in j_boxes]
    ys = [p[1] for p in j_boxes]
    zs = [p[2] for p in j_boxes]

    scatter = ax.scatter(xs, ys, zs, s=40, c="blue", depthshade=True, zorder=2)
    azim = 45
    elev = 25
    ax.view_init(elev=elev, azim=azim)

    line_collection = Line3DCollection([], colors='white', linewidths=1.5, zorder=1)
    ax.add_collection(line_collection)

    edges_array = []
    epsilon = 0.01

    # -----------------------------
    # ANIMATION FUNCTION
    # -----------------------------
    def animate(event=None):
        nonlocal azim
        for (a, b) in accepted_edges:
            pa = viz_get_circuit(a)
            pb = viz_get_circuit(b)
            if pa != pb:
                viz_circuits[pa].update(viz_circuits[pb])
                del viz_circuits[pb]

            # Update node colors
            sizes = [len(c) for c in viz_circuits]
            max_size = max(sizes)
            min_size = min(sizes)
            colors = []
            for j in j_boxes:
                ci = viz_get_circuit(j)
                size = len(viz_circuits[ci])
                t = (size - min_size) / max(1, max_size - min_size)
                r = t
                g = 0
                b_ = 1 - t
                colors.append([r, g, b_])
            colors = np.array(colors)
            scatter.set_facecolor(colors)
            scatter.set_edgecolor(colors)

            edges_array.append([(a[0], a[1], a[2]-epsilon), (b[0], b[1], b[2]-epsilon)])
            line_collection.set_segments(edges_array)

            azim += 0.5
            ax.view_init(elev=elev, azim=azim)
            plt.pause(0.001)

    # -----------------------------
    # BUTTON SETUP
    # -----------------------------
    ax_button = plt.axes([0.8, 0.02, 0.15, 0.05])
    button = Button(ax_button, 'Start Animation', color='gray', hovercolor='lightgreen')
    button.on_clicked(animate)

    # Keep GUI running until closed
    plt.show()
    return p1, p2

if __name__ == "__main__":
    p1, p2 = solve()
    print("Part 1:", p1)
    print("Part 2:", p2)
